version: 2

tools:
  eslint: &eslint
    lint-command: "eslint -f unix --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-source: "eslint"
    lint-stdin: true

languages:
  javascript:
    - <<: *eslint
  javascriptreact:
    - <<: *eslint
  typescript:
    - <<: *eslint
  typescriptreact:
    - <<: *eslint
