'$schema' = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$character"""

[directory]
style = 'blue'

[character]
success_symbol = '[\$](purple)'
error_symbol = '[\$](red)'

[git_branch]
format = '[$branch]($style)'
style = 'green'

[package]
disabled = true
