'$schema' = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
${custom.git}\
${custom.jj}\
$line_break\
$character"""

[directory]
style = 'blue'

[character]
success_symbol = '[\$](purple)'
error_symbol = '[\$](red)'

[custom.git]
detect_folders = ['.git', '!.jj']
style = 'green'
symbol = 'git'

[custom.jj]
detect_folders = ['.jj']
style = 'green'
symbol = 'jj'

[git_branch]
disabled = true

[package]
disabled = true
