theme = 'catppuccin_mocha'

[editor]
auto-completion = false
color-modes = true
popup-border = 'all'

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ['line-numbers', 'spacer']

[editor.inline-diagnostics]
cursor-line = 'warning'

[editor.statusline]
right = ['diagnostics', 'selections', 'file-type']

[editor.statusline.mode]
insert = 'I'
normal = 'N'
select = 'S'
[keys.normal.space.l]
c = ':sh forgelink copy "%{file_path_absolute}:%{selection_line_start}-%{selection_line_end}"'
o = ':sh forgelink open "%{file_path_absolute}:%{selection_line_start}-%{selection_line_end}"'
