[editor]
auto-completion = false
end-of-line-diagnostics = 'disable'
popup-border = 'all'

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ['line-numbers', 'spacer']

[editor.gutters.line-numbers]
min-width = 1

[editor.statusline]
right = ['diagnostics', 'selections', 'file-type']

[theme]
dark = 'wolf-alabaster-dark'
light = 'wolf-alabaster-light'
