[language-server.rust-analyzer.config.check]
command = 'clippy'

[[language]]
name = 'clojure'
auto-format = true

[[language]]
name = 'css'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'html'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'java'
auto-format = true
formatter = { command = 'google-java-format', args = ['-'] }

[[language]]
name = 'javascript'
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'json'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'jsx'
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'markdown'
auto-format = true

[[language]]
name = 'python'
language-servers = ['basedpyright', 'ruff']
auto-format = true

[[language]]
name = 'toml'
auto-format = true

[[language]]
name = 'tsx'
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'typescript'
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }
