[language-server.rumdl]
command = 'rumdl'
args = ['server']

[language-server.phpantom]
command = 'phpantom_lsp'

[language-server.rust-analyzer.config.check]
command = 'clippy'

[language-server.vtsls]
command = 'vtsls'
args = ['--stdio']

[language-server.vtsls.config.vtsls]
autoUseWorkspaceTsdk = true

[language-server.vtsls.config.javascript.preferences]
importModuleSpecifier = 'non-relative'
importModuleSpecifierEnding = 'minimal'

[language-server.vtsls.config.typescript.preferences]
autoImportFileExcludePatterns = [
  'next/router.d.ts',
  'next/dist/client/router.d.ts',
  'lucide-react',
]
importModuleSpecifier = 'non-relative'
importModuleSpecifierEnding = 'minimal'

[[language]]
name = 'clojure'
formatter = { command = 'cljstyle', args = ['pipe'] }
auto-format = true

[[language]]
name = 'css'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'graphql'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }
auto-format = true

[[language]]
name = 'html'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'hurl'
auto-format = true

[[language]]
name = 'java'
auto-format = true
formatter = { command = 'google-java-format', args = ['-'] }

[[language]]
name = 'javascript'
language-servers = ['vtsls', 'oxlint-language-server']
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'json'
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'jsx'
language-servers = ['vtsls', 'oxlint-language-server', 'tailwindcss-ls']
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'kotlin'
language-servers = ['kotlin-lsp']

[[language]]
name = 'markdown'
language-servers = ['rumdl']
auto-format = true

[[language]]
name = 'php'
language-servers = ['phpantom']
auto-format = true

[[language]]
name = 'python'
language-servers = ['basedpyright', 'ruff']
auto-format = true

[[language]]
name = 'toml'
auto-format = true

[[language]]
name = 'tsx'
language-servers = ['vtsls', 'oxlint-language-server', 'tailwindcss-ls']
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }

[[language]]
name = 'typescript'
language-servers = ['vtsls', 'oxlint-language-server']
auto-format = true
formatter = { command = 'prettier', args = [
  '--stdin-filepath',
  '%{buffer_name}',
] }
