[settings]
experimental = true
legacy_version_file = false

[tools]
node = '22.21.1'
python = '3.14.2'
rust = { version = '1.91.1', components = 'clippy,rust-analyzer' }
'ubi:terror/just-lsp' = 'latest'
'ubi:weavejester/cljfmt' = 'latest'
