confirm-before-quit = false
option-as-alt = 'left'
padding-x = 10
padding-y = [10, 10]

[adaptive-theme]
dark = 'Modus Vivendi'
light = 'Modus Operandi'

[editor]
program = '/opt/homebrew/bin/hx'

[fonts]
family = 'Berkeley Mono'
hinting = false
size = 12

[navigation]
mode = 'NativeTab'
use-current-path = true
use-split = false
