# Ef-Dark
[colors]
background = '#000000'
foreground = '#d0d0d0'

cursor = '#ff76ff'

selection-background = '#2a234a'
selection-foreground = '#d0d0d0'

black = '#1a1a1a'
blue = '#3f95f6'
cyan = '#4fbaef'
green = '#0faa26'
magenta = '#d369af'
red = '#ef6560'
white = '#d0d0d0'
yellow = '#bf9032'

light-black = '#4b4b4b'
light-blue = '#029fff'
light-cyan = '#1dbfcf'
light-green = '#00a692'
light-magenta = '#af85ff'
light-red = '#ff5a7a'
light-white = '#857f8f'
light-yellow = '#df8a5a'
