# Ef-Light
[colors]
background = '#ffffff'
foreground = '#202020'

cursor = '#0033cc'

selection-background = '#bfefff'
selection-foreground = '#202020'

black = '#efefef'
blue = '#3740cf'
cyan = '#1f6fbf'
green = '#217a3c'
magenta = '#ba35af'
red = '#d3303a'
white = '#202020'
yellow = '#a45f22'

light-black = '#b3b3b3'
light-blue = '#065fff'
light-cyan = '#1f77bb'
light-green = '#008858'
light-magenta = '#6052cf'
light-red = '#d50f7f'
light-white = '#70627f'
light-yellow = '#b65050'
