# Modus Operandi
[colors]
background = '#ffffff'
foreground = '#000000'

cursor = '#000000'

selection-background = '#f8e6f5'
selection-foreground = '#000000'

black = '#f2f2f2'
blue = '#0031a9'
cyan = '#005e8b'
green = '#006800'
magenta = '#721045'
red = '#a60000'
white = '#000000'
yellow = '#6f5500'

light-black = '#c4c4c4'
light-blue = '#0000b0'
light-cyan = '#005f5f'
light-green = '#00663f'
light-magenta = '#531ab6'
light-red = '#a0132f'
light-white = '#595959'
light-yellow = '#7a4f2f'
