inherits = 'modus_operandi'

'ui.cursor.match' = { bg = 'bg-main' }
'ui.gutter' = { bg = 'bg-main' }
'ui.gutter.selected' = { bg = 'bg-main' }
'ui.help' = { bg = 'bg-main' }
'ui.linenr' = { bg = 'bg-main', fg = 'fg-main', modifiers = ['dim'] }
'ui.linenr.selected' = { bg = 'bg-main', fg = 'fg-main', modifiers = ['bold'] }
'ui.menu' = { bg = 'bg-main' }
'ui.popup' = { bg = 'bg-main' }
'ui.popup.info' = { bg = 'bg-main' }
'ui.statusline.insert' = { bg = 'green-warmer', fg = 'bg-main' }
'ui.statusline.normal' = { bg = 'blue-warmer', fg = 'bg-main' }
'ui.statusline.select' = { bg = 'magenta-warmer', fg = 'bg-main' }
