auto_sync = false
enter_accept = true
filter_mode = 'host'
filter_mode_shell_up_key_binding = 'session'
inline_height = 0
prefers_reduced_motion = true
show_help = false
show_tabs = false
update_check = false
