#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

fd -td -d1 | sort -f | while read -r dir; do
    if [ -d "$dir/.git" ]; then
        basename "${dir%/}"
        (cd "$dir" && git "$@")
        echo
    fi
done
