[default, private]
commands:
    @just -g --list

# Generate client app
client-app name='org.passen/boof':
    @clojure -Sdeps '{:deps {org.passen/deps-client-app {:local/root "deps-client-app"}}}' -X:new :template org.passen/deps-client-app :name {{name}}

# Generate library app
library-app name='org.passen/dood':
    @clojure -Sdeps '{:deps {org.passen/deps-library-app {:local/root "deps-library-app"}}}' -X:new :template org.passen/deps-library-app :name {{name}}

# Generate server app
server-app name='org.passen/foob':
    @clojure -Sdeps '{:deps {org.passen/deps-server-app {:local/root "deps-server-app"}}}' -X:new :template org.passen/deps-server-app :name {{name}}
