[colors]
ansi = [
    '#595959',
    '#ff8059',
    '#44bc44',
    '#d0bc00',
    '#2fafff',
    '#feacd0',
    '#00d3d0',
    '#a6a6a6',
]
background = '#000000'
brights = [
    '#595959',
    '#ff8059',
    '#44bc44',
    '#d0bc00',
    '#2fafff',
    '#feacd0',
    '#00d3d0',
    '#a6a6a6',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#361586'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Modus Vivendi'
