[colors]
ansi = [
  '#000000',
  '#ff8059',
  '#44bc44',
  '#d0bc00',
  '#2fafff',
  '#feacd0',
  '#00d3d0',
  '#a6a6a6',
]
background = '#000000'
brights = [
  '#595959',
  '#ef8b50',
  '#00c06f',
  '#c0c530',
  '#79a8ff',
  '#b6a0ff',
  '#6ae4b9',
  '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#240f55'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Modus Vivendi'
