[colors]
ansi = [
  '#595959',
  '#a60000',
  '#005e00',
  '#813e00',
  '#0030a6',
  '#721045',
  '#00538b',
  '#a6a6a6',
]
background = '#ffffff'
brights = [
  '#595959',
  '#a60000',
  '#005e00',
  '#813e00',
  '#0030a6',
  '#721045',
  '#00538b',
  '#a6a6a6',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#ffffff'
foreground = '#000000'
selection_bg = '#bcbcbc'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Modus Operandi'
