[colors]
ansi = [
  '#000000',
  '#a60000',
  '#005e00',
  '#813e00',
  '#0031a9',
  '#721045',
  '#00538b',
  '#a6a6a6',
]
background = '#ffffff'
brights = [
  '#595959',
  '#972500',
  '#145c33',
  '#70480f',
  '#2544bb',
  '#5317ac',
  '#005a5f',
  '#ffffff',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#ffffff'
foreground = '#000000'
selection_bg = '#efdfff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Modus Operandi'
