[bat.files]
'bat/config' = '~/.config/bat/config'

[emacs.files]
'emacs/early-init.el' = '~/.config/emacs/early-init.el'
'emacs/init.el' = '~/.config/emacs/init.el'

[fish.files]
'fish/conf.d/brew.fish' = '~/.config/fish/conf.d/brew.fish'
'fish/conf.d/editor.fish' = '~/.config/fish/conf.d/editor.fish'
'fish/conf.d/postexec_echo.fish' = '~/.config/fish/conf.d/postexec_echo.fish'
'fish/conf.d/xdg.fish' = '~/.config/fish/conf.d/xdg.fish'
'fish/functions/edit.fish' = '~/.config/fish/functions/edit.fish'
'fish/functions/emacs.fish' = '~/.config/fish/functions/emacs.fish'
'fish/functions/fish_greeting.fish' = '~/.config/fish/functions/fish_greeting.fish'
'fish/functions/fish_prompt.fish' = '~/.config/fish/functions/fish_prompt.fish'

[git.files]
'git/ignore' = '~/.config/git/ignore'

[helix.files]
'helix/config.toml' = '~/.config/helix/config.toml'
'helix/languages.toml' = '~/.config/helix/languages.toml'

[hushlogin.files]
'hushlogin/hushlogin' = '~/.hushlogin'

[jj.files]
'jj/config.toml' = '~/.config/jj/config.toml'

[kak.files]
'kak/colors/catppuccin-mocha.kak' = '~/.config/kak/colors/catppuccin-mocha.kak'
'kak/config/options.kak' = '~/.config/kak/config/options.kak'
'kak/filetypes/python.kak' = '~/.config/kak/filetypes/python.kak'
'kak/filetypes/rust.kak' = '~/.config/kak/filetypes/rust.kak'
'kak/kakrc' = '~/.config/kak/kakrc'
'kak/utils/lsp.kak' = { target = '~/.config/kak/utils/lsp.kak', type = 'symbolic' }
'kak/utils/lsp/basedpyright.toml' = '~/.config/kak/utils/lsp/basedpyright.toml'
'kak/utils/lsp/ruff.toml' = '~/.config/kak/utils/lsp/ruff.toml'

[mise.files]
'mise/config.toml' = '~/.config/mise/config.toml'

[pi.files]
'pi/agent/settings.json' = '~/.pi/agent/settings.json'

[wezterm.files]
'wezterm/wezterm.lua' = '~/.config/wezterm/wezterm.lua'
