[atuin.files]
'atuin/config.toml' = '~/.config/atuin/config.toml'

[bat.files]
'bat/config' = '~/.config/bat/config'

[clojure.files]
'clojure/deps.edn' = '~/.config/clojure/deps.edn'

[efm-langserver.files]
'efm-langserver/config.yaml' = '~/.config/efm-langserver/config.yaml'

[emacs.files]
'emacs/early-init.el' = '~/.config/emacs/early-init.el'
'emacs/init.el' = '~/.config/emacs/init.el'

[erdtree.files]
'erdtree/erdtree.toml' = '~/.config/erdtree/.erdtree.toml'

[ghostty.files]
'ghostty/config' = '~/.config/ghostty/config'
'ghostty/themes/Ef-Dark' = '~/.config/ghostty/themes/Ef-Dark'
'ghostty/themes/Ef-Light' = '~/.config/ghostty/themes/Ef-Light'

[git.files]
'git/config' = '~/.config/git/config'
'git/ignore' = '~/.config/git/ignore'

[gitu.files]
'gitu/config.toml' = '~/.config/gitu/config.toml'

[helix.files]
'helix/config.toml' = '~/.config/helix/config.toml'
'helix/languages.toml' = '~/.config/helix/languages.toml'
'helix/themes/base16_statusbar.toml' = '~/.config/helix/themes/base16_statusbar.toml'

[jj.files]
'jj/config.toml' = '~/.config/jj/config.toml'

[just.files]
'just/justfile' = { target = '~/.config/just/justfile', type = 'symbolic' }

[leiningen.files]
'leiningen/profiles.clj' = '~/.lein/profiles.clj'

[mise.files]
'mise/config.toml' = '~/.config/mise/config.toml'

[starship.files]
'starship/starship.toml' = '~/.config/starship.toml'

[zsh.files]
'zsh/zshenv.zsh' = '~/.zshenv'
'zsh/zshrc.zsh' = '~/.zshrc'
