[bat.files]
'bat/config' = '~/.config/bat/config'

[emacs.files]
'emacs/early-init.el' = '~/.config/emacs/early-init.el'
'emacs/init.el' = '~/.config/emacs/init.el'

[fish.files]
'fish/conf.d/brew.fish' = '~/.config/fish/conf.d/brew.fish'
'fish/conf.d/editor.fish' = '~/.config/fish/conf.d/editor.fish'
'fish/conf.d/postexec_echo.fish' = '~/.config/fish/conf.d/postexec_echo.fish'
'fish/conf.d/xdg.fish' = '~/.config/fish/conf.d/xdg.fish'
'fish/functions/edit.fish' = '~/.config/fish/functions/edit.fish'
'fish/functions/emacs.fish' = '~/.config/fish/functions/emacs.fish'
'fish/functions/fish_greeting.fish' = '~/.config/fish/functions/fish_greeting.fish'
'fish/functions/fish_prompt.fish' = '~/.config/fish/functions/fish_prompt.fish'

[git.files]
'git/ignore' = '~/.config/git/ignore'

[helix.files]
'helix/config.toml' = '~/.config/helix/config.toml'
'helix/languages.toml' = '~/.config/helix/languages.toml'
'helix/themes/catppuccin_mocha.toml' = '~/.config/helix/themes/catppuccin_mocha.toml'

[hushlogin.files]
'hushlogin/hushlogin' = '~/.hushlogin'

[jj.files]
'jj/config.toml' = '~/.config/jj/config.toml'

[kak.files]
'kak/colors/catppuccin-mocha.kak' = '~/.config/kak/colors/catppuccin-mocha.kak'
'kak/config/clipboard.kak' = '~/.config/kak/config/clipboard.kak'
'kak/config/core.kak' = '~/.config/kak/config/core.kak'
'kak/config/find.kak' = '~/.config/kak/config/find.kak'
'kak/config/init.kak' = '~/.config/kak/config/init.kak'
'kak/filetypes/init.kak' = '~/.config/kak/filetypes/init.kak'
'kak/filetypes/markdown.kak' = '~/.config/kak/filetypes/markdown.kak'
'kak/filetypes/python.kak' = '~/.config/kak/filetypes/python.kak'
'kak/filetypes/rust.kak' = '~/.config/kak/filetypes/rust.kak'
'kak/kakrc' = '~/.config/kak/kakrc'
'kak/lsp/basedpyright.toml' = '~/.config/kak/lsp/basedpyright.toml'
'kak/lsp/init.kak' = '~/.config/kak/lsp/init.kak'
'kak/lsp/rumdl.toml' = '~/.config/kak/lsp/rumdl.toml'
'kak/lsp/ruff.toml' = '~/.config/kak/lsp/ruff.toml'

[mise.files]
'mise/config.toml' = '~/.config/mise/config.toml'

[pi.files]
'pi/agent/settings.json' = '~/.pi/agent/settings.json'
