source "%val{config}/filetypes/go.kak"
source "%val{config}/filetypes/javascript.kak"
source "%val{config}/filetypes/markdown.kak"
source "%val{config}/filetypes/php.kak"
source "%val{config}/filetypes/python.kak"
source "%val{config}/filetypes/rust.kak"
