theme = 'dpassen'

[editor]
auto-completion = false
color-modes = true
end-of-line-diagnostics = 'hint'
popup-border = 'all'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ['spacer', 'diagnostics', 'line-numbers', 'spacer']

[editor.gutters.line-numbers]
min-width = 1

[editor.inline-diagnostics]
cursor-line = 'warning'

[editor.statusline.mode]
insert = 'INSERT'
normal = 'NORMAL'
select = 'SELECT'
