theme = 'base16_transparent'

[editor]
color-modes = true
end-of-line-diagnostics = 'hint'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = 'warning'

[editor.statusline.mode]
insert = 'INSERT'
normal = 'NORMAL'
select = 'SELECT'
